### ISSUE TITLE
xMrVizzy/button-toolbar not available any longer

### ISSUE THREAD

**Issue by tux2000** [hacs/default#729] opened 2020-12-05 13:10 UTC
xMrVizzy/button-toolbar is not available any longer. This results in the error in home assistant:

```
Logger: custom_components.hacs.repository.plugin.xMrVizzy.button-toolbar
Source: custom_components/hacs/helpers/functions/validate_repository.py:40
Integration: HACS (documentation, issues)
First occurred: 7:09:29 AM (1 occurrences)
Last logged: 7:09:29 AM
GitHub returned 404 for https://api.github.com/repos/xMrVizzy/button-toolbar 
```

The repository is listed here: https://github.com/hacs/default/blob/9af12399b38aa51ec37b3779be4f3ee1d5d07d16/plugin#L195 but apparently its not as easy as removing that line only (see https://github.com/hacs/default/pull/728).

**Comment by ludeeus** [comment] 2020-12-05 14:06
duplicate of https://github.com/hacs/integration/issues/1696

**Closed by ludeeus** 2020-12-05 14:06 UTC
