### ISSUE TITLE
Cannot read property 'selectedItem' of undefined(CUSTOM REPOSITORIES)

### ISSUE THREAD

**Issue by fineemb** [hacs/default#464] opened 2020-05-21 16:02 UTC
## Describe why you are flagging this
CUSTOM REPOSITORIES
add  erpositories -- save
````
Uncaught TypeError: Cannot read property 'selectedItem' of undefined
    at HTMLElement.Save (frontend-20200426112021.js:21594)
    at EventPart.handleEvent (frontend-20200426112021.js:1090)
    at HTMLElement.EventPart.__boundHandleEvent (frontend-20200426112021.js:1056)
````
_This template should **only** be used if a repository **needs** to be removed/blacklisted from HACS_

**Comment by ludeeus** [comment] 2020-05-21 16:02
invalid use of flags, duplicate of https://github.com/hacs/integration/issues/1143

**Closed by ludeeus** 2020-05-21 16:02 UTC
Labels: invalid
